### ISSUE TITLE
Feature: Sync Names with PCO Services

### ISSUE THREAD

**Issue by afoster757** [karlcswanson/micboard#32]
Hey Karl,

I would love to work with you to extend the features of micboard to sync the name assignments with PCO Services. I feel this would be extremely helpful to most smaller churches since typically they don't assign names inside of Workbench.

What are your thoughts?

**Comment by karlcswanson** [comment]
Hey Adam,
There is already a function to name the channels within micboard.  There is some documentation [here](https://github.com/karlcswanson/micboard/blob/master/docs/configuration.md#extended-names).  There is also a "bulk name importer" that lets you paste in a block of text from a document and fill in names from there.  Its been a while since i looked at the template section of PCO, but you might be able to format part of a template with an output that would work with that input.  I did look at PCO when I first started on the project, it would becool to get pictures that way.  We were using google sheets at the time & had some great photos from our photography team, so I ended up sticking to the simple text input.

**Comment by afoster757** [comment]
Hey, so I was able to clone your repo as a starting point and build out additional modules to support bringing in PCO assignments. I also updated the images folder to sync with a Dropbox folder on a schedule so I could at least easily update that dynamically. 

 I should publish it as a fork so you can look at it. Prob needs a lot of polishing. 

Thank you so much for this build.

**Comment by karlcswanson** [comment]
The dropbox sync is a cool way to do that!  I would be interested in looking at your changes, not sure if I'd push any updates to the main thing anytime soon.  No test hardware and I'd like to rewrite much of it.
